version: 0.2

phases:
  install:
    commands:
      - echo $CODEBUILD_SOURCE_VERSION
      - echo $CODEBUILD_WEBHOOK_BASE_REF
      - yarn
  build:
    commands:
      - yarn build
  post_build:
    commands:
      - echo build is `date`
artifacts:
  files:
    - "**/*"
  name: build-output
  discard-paths: no
  base-directory: build
  s3-prefix: code-build-outputs
  secondary-artifacts:
    cloudformationfile:
      files:
        - cloud-formtation.json
      name: cloud-formtation
      discard-paths: no
