version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ls
      - echo build is completed
artifacts:
  files:
    - "**/*"
  name: build-output
  discard-paths: no
  base-directory: build
  secondary-artifacts:
    cloudformationfiles:
      files:
        - "**/*"
      name: cloud-formation-files-1
      discard-paths: no
      base-directory: cloud-formations
