version: 0.2

phases:
  install:
    commands:
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - npm install
  build:
    commands:
      - npm build
  post_build:
    commands:
      - echo build is completed
artifacts:
  files:
    - "build/**/*"
  name: build-output
  discard-paths: no
