version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  source-branch-operations:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: $CIRCLE_BRANCH
          command: echo $CIRCLE_BRANCH
      - run:
          name: TESTVAT=$("TESTVARVALYE")
          command: TESTVAT=$("TESTVARVALYE")
      - run:
          name: echo $TESTVAT
          command: echo $TESTVAT
  deploy-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: echo source branch
          command: echo $SOURCEBRANCH

workflows:
  aws-cli:
    jobs:
      - source-branch-operations
      - deploy-stack