version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
  # mem: circleci/rememborb@0.0.2

jobs:
  source-branch-operations:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: TESTVAL=TESTVALUE
          command: TESTVAL=TESTVALUE
      # - mem/remember:
      #     env_var: TESTVAL
      #     value: $TESTVAL
      - run:
          name: echo $TESTVAL
          command: echo $TESTVAL
  deploy-stack:
    executor: aws-cli/default
    steps:
      - checkout
      # - mem/recall:
      #     env_var: TESTVAL
      # - run:
      #     name: echo $TESTVAL
      #     command: echo $TESTVAL
workflows:
  version: 2
  aws-cli:
    jobs:
      - source-branch-operations
      - deploy-stack:
          requires:
            - source-branch-operations
      