version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  source-branch-operations:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: echo source branch
          command: git show-branch | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//'
      - run:
          name: set source branch
          command: SOURCEBRANCH=$(git show-branch | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')
      - run:
          name: echo source branch variable
          command: echo $SOURCEBRANCH
  deploy-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: echo source branch
          command: echo $SOURCEBRANCH

workflows:
  aws-cli:
    jobs:
      - source-branch-operations
      - deploy-stack