version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  source-branch-operations:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: $CIRCLE_BRANCH
          command: echo $CIRCLE_BRANCH
      - run:
          name: TESTVAL=TESTVALUE
          command:  echo "export TESTVAL=TESTVALUE" >> $BASH_ENV 
      - run:
          name: echo $TESTVAL
          command: echo $TESTVAL
  deploy-stack:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: echo source branch
          command: echo $TESTVAL
workflows:
  version: 2
  aws-cli:
    jobs:
      - source-branch-operations
      - deploy-stack:
          requires:
            - source-branch-operations
      