version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1
jobs:
  config-aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      
      - aws-cli/setup:
          profile-name: default
      - run:
          name: print directory
          command: ls
      - run:
          name: print version of git
          command: git --version
      - run: 
          aws lambda list-functions

workflows:
  aws-cli:
    jobs:
      - config-aws-cli