// WARNING: DO NOT EDIT.  This file is automatically generated
// Written by undefined on 2021-09-23T13:56:28.573Z

interface IAWSAmplifyFederatedConfiguration {
  google_client_id?: string
  facebook_app_id?: string
  amazon_client_id?: string
}

interface IAWSAmplifyCloudLogicConfiguration {
  [index: number]: {
    endpoint: string
    name: string
    region: string
  }
}

interface IAWSAmplifyConfiguration {
  aws_appsync_authenticationType?: string
  aws_appsync_graphqlEndpoint?: string
  aws_appsync_region?: string
  aws_cognito_identity_pool_id?: string
  aws_cognito_region?: string
  aws_cloud_logic_custom?: IAWSAmplifyCloudLogicConfiguration
  aws_project_region: string
  aws_user_files_s3_bucket?: string
  aws_user_files_s3_bucket_region?: string
  aws_user_pools_id?: string
  aws_user_pools_web_client_id?: string
  aws_user_pools_web_client_secret?: string
  federated?: IAWSAmplifyFederatedConfiguration
}

const awsmobile: IAWSAmplifyConfiguration = {
  aws_cloud_logic_custom: [
    {
      endpoint: "",
      name: "ApiGatewayRestApi",
      region: "",
    },
    {
      endpoint: "",
      name: "acpsprint19cognitoadminapi",
      region: "",
    },
    {
      endpoint: "",
      name: "acpsprint19dynamodbapi",
      region: "",
    },
  ],
  aws_cognito_identity_pool_id: "",
  aws_cognito_region: "",
  aws_project_region: "",
  aws_user_files_s3_bucket: "",
  aws_user_files_s3_bucket_region: "",
}

export default awsmobile
