import * as React from "react"
import { Link } from "wouter"
import { Box, Typography, makeStyles } from "@material-ui/core"
import { Routes } from "acp/src/constants/routes"

const useStyles = makeStyles({
  "@global": {
    "#root": {
      minHeight: `100%`,
      display: `flex`,
      flexFlow: `column`,
    },
  },
  main: {
    margin: "auto",
  },
})

export const Layout = (): React.ReactElement => {
  const classes = useStyles()
  return (
    <Box className={classes.main} component="main">
      <Typography variant="h6">This is the main Layout of the React application generated by ACP CLI.</Typography>
      <Typography variant="body1" align="center">
        If you are looking for the admin dashboard, click <Link to={Routes.Dashboard}>here</Link>
      </Typography>
    </Box>
  )
}
